# Generated by Django 5.1.3 on 2024-11-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='produk',
            new_name='id_Produk',
        ),
        migrations.RenameField(
            model_name='transaksi',
            old_name='is_pay',
            new_name='ispay',
        ),
        migrations.RenameField(
            model_name='transaksi',
            old_name='total_harga',
            new_name='totalHarga',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='user',
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='jumlah',
            field=models.IntegerField(),
        ),
    ]
